export type VaSeeker = {
  id: string;
  name: string;
  company: string;
  email: string | null;
  agreed_payment_terms: boolean;
  agreed_accurate_info: boolean;
  agreed_contact: boolean;
  agreed_email_contract: boolean;
  notes: string | null;
  va_id: string | null;
  va_name: string | null;
  va_niche: string | null;
  match_score: number | null;
  category: string | null;
  hours: string | null;
  budget: string | null;
  project_details: string | null;
  created_at: string;
};
